### PR TITLE
Restructure theme

### PR DESCRIPTION
**Pull request by adminazhar**

### CODE REVIEW

**Comment by wiryawanadipa** [comment]
thanks for the suggestion, definitely helpful.

**Comment by adminazhar** [comment]
@wiryawanadipa Test it and let me know, i will push another update to update the get_header/footer function with get_template_parts()

**Comment by wiryawanadipa** [comment]
I already test it, and already doing get_template_parts right now. I'm updating all of it right now

**Comment by adminazhar** [comment]
@wiryawanadipa Perfect, i thought about doing it but didn't got enough time 😅

**Comment by wiryawanadipa** [comment]
it's alright, thanks for the help though. appreciate it. will update it in the morning

**Comment by wiryawanadipa** [comment]
I decide to push it now. good night

**Comment by adminazhar** [comment]
@wiryawanadipa perfect!!! 
When you get time check Roots Sage, we use in our daily development for our organization.

**Pull request merged**
